@tool
class_name AIStudioGodotAnimTools
extends RefCounted

## Tools that fix animation names and animations in place, plus two editor
## escape hatches:
##   godot_animation_rename           rename animations / libraries (+ references)
##   godot_animation_find_references  find (and rewrite) uses of animation names
##   godot_animation_edit             track paths, bones, loop, length, speed, copy/move
##   godot_import_animation_names     names inside imported models (.glb/.fbx/...)
##   godot_run_editor_script          run a one-off GDScript in the editor
##   godot_editor_log                 editor errors, Output panel, debugger errors
##
## Edits to the scene open in the editor go through the editor's undo history.
## Other scenes are instantiated, changed, repacked and saved (the same way as
## the godot_scene_* tools), and standalone AnimationLibrary/SpriteFrames files
## are saved in place.

var host = null   # AIStudioGodotTools (untyped to avoid a cyclic class reference)

const MODEL_EXTS := ["glb", "gltf", "fbx", "blend", "dae", "obj", "ufbx"]
const REF_EXTS := ["gd", "cs", "tscn", "tres"]
const MAX_REFS := 400
const MAX_REF_FILE_BYTES := 2_000_000
const MAX_RESULT_CHARS := 20000
const GENERATED_MARK := "Generated by AI Studio (godot_import_animation_names)"
const LOOP_MODES := {"none": Animation.LOOP_NONE, "linear": Animation.LOOP_LINEAR, "pingpong": Animation.LOOP_PINGPONG}
## Properties that store an animation name (players, sprites, tree nodes).
const NAME_PROPS := ["animation", "autoplay", "assigned_animation", "current_animation", "animation_name",
	"default_animation"]

var _literal_re: RegEx = RegEx.create_from_string("(&|\\^)?\"((?:[^\"\\\\]|\\\\.)*)\"|'((?:[^'\\\\]|\\\\.)*)'")
var _use_re: RegEx = RegEx.create_from_string("(?i)(play|queue|anim|travel|\\.start\\s*\\(|seek|sprite_frames|frames)")
var _prop_re: RegEx = RegEx.create_from_string("^\\s*(animation|autoplay|assigned_animation|current_animation|animation_name|default_animation)\\s*=")
var _def_re: RegEx = RegEx.create_from_string("^\\s*&?\"[^\"]*\"\\s*:\\s*(SubResource|ExtResource|Animation)|\"name\"\\s*:\\s*&?\"")
var _state_re: RegEx = RegEx.create_from_string("^\\s*(states/|transitions|start_node|end_node)")


func _init(host_tools) -> void:
	host = host_tools


# ---------------------------------------------------------------------------
# registration
# ---------------------------------------------------------------------------

func register() -> void:
	var map_schema := {"type": "object", "additionalProperties": {"type": "string"},
		"description": "Exact renames, old -> new, e.g. {\"mixamo_com\": \"run\", \"Armature|Take 001\": \"idle\"}. Keys may also be \"library/anim\"."}
	var rule_props := {
		"renames": map_schema,
		"cleanup": {"type": "string", "enum": ["none", "strip_prefix", "snake_case"], "default": "none",
			"description": "Automatic clean-up for names without an exact rename: strip_prefix drops everything up to the last '|' (\"Armature|Run\" -> \"Run\"); snake_case also lowercases and joins words with '_' (\"Armature|Run Fast\" -> \"run_fast\")."},
		"pattern": host._str("Optional regex applied after cleanup, e.g. \"^CharacterArmature_\" or \"\\\\s+\"."),
		"replacement": host._str("Replacement for 'pattern' ($1 groups allowed; default empty)."),
	}

	var rename_props := {
		"source": host._str("Scene (.tscn) or AnimationLibrary / SpriteFrames resource (.tres/.res). Default: the scene open in the editor (undoable)."),
		"node_path": host._str("Only this AnimationPlayer / AnimationTree / AnimatedSprite node (default: all in the scene)."),
		"library": host._str("Only this animation library (\"\" = the default library). Omit for all libraries."),
		"target": {"type": "string", "enum": ["animations", "libraries"], "default": "animations",
			"description": "Rename animations (default) or the library keys of the players."},
		"update_references": host._bool("Also rewrite the old names elsewhere: autoplay / assigned animation, AnimationTree nodes and AnimatedSprite properties in the scene, and play(\"old\")-style uses in scripts, scenes and resources across the project.", true),
		"dry_run": host._bool("Only show what would change.", false),
	}
	rename_props.merge(rule_props)
	host._add("godot_animation_rename",
		"Rename animations (or animation libraries) in an AnimationPlayer/AnimationTree, an AnimationLibrary or SpriteFrames (AnimatedSprite2D/3D), by exact names, automatic clean-up of names such as \"Armature|Run\" or \"CharacterArmature|Walk\", or a regex. Checks for invalid characters and clashes, and by default updates every reference to the old names. For animations inside an imported .glb/.fbx use godot_import_animation_names instead (those names are restored on reimport).",
		host._obj(rename_props),
		func(a): return _tool_rename(a), false, "animation")
	host._set_safe_fn("godot_animation_rename", func(a): return bool(a.get("dry_run", false)))

	host._add("godot_animation_find_references",
		"Find where animation names are used across the project (res://addons is skipped): play()/queue()/travel() and other string uses in .gd/.cs scripts, autoplay/assigned_animation/animation properties, AnimationTree nodes and AnimatedSprite animations in .tscn/.tres, library and SpriteFrames definitions, and state-machine state names. With 'renames' and apply=true it rewrites the uses (not definitions or state names; backups go to user://ai_studio/backups).",
		host._obj({
			"names": {"type": "array", "items": {"type": "string"}, "description": "Animation names to look for (\"run\" or \"library/run\"). Not needed when 'renames' is given."},
			"renames": map_schema,
			"any_library": host._bool("Also match the name under any library prefix (\"run\" matches \"moves/run\").", false),
			"apply": host._bool("Rewrite the matches to the new names from 'renames'.", false),
			"include_possible": host._bool("When applying, also rewrite 'maybe' matches (a string equal to the name in a line without animation keywords).", false),
		}),
		func(a): return _tool_find_references(a), true, "animation")
	host._set_safe_fn("godot_animation_find_references", func(a): return not bool(a.get("apply", false)))

	host._add("godot_animation_edit",
		"Edit existing animations in place (no copies): swap a node-path prefix in the track paths (e.g. \"Armature/Skeleton3D\" -> \"Skeleton3D\"), rename bones in bone tracks (exact map or regex, e.g. strip \"mixamorig:\"), remove tracks that point at missing nodes/bones or match a regex, set loop mode, length or playback speed, and copy or move animations to another library (in the same player or a .tres AnimationLibrary). Use godot_animation_tracks first to see what is broken.",
		host._obj({
			"source": host._str("Scene (.tscn) or AnimationLibrary / Animation resource. Default: the scene open in the editor (undoable)."),
			"node_path": host._str("Only this AnimationPlayer/AnimationTree (default: all)."),
			"library": host._str("Only this library (\"\" = default). Omit for all."),
			"animation": host._str("Animation name (\"run\" or \"library/run\"), or \"*\" for every animation in scope."),
			"path_prefix_from": host._str("Track-path prefix to replace, e.g. \"Armature/Skeleton3D\"."),
			"path_prefix_to": host._str("New prefix (empty = remove the prefix)."),
			"bone_renames": {"type": "object", "additionalProperties": {"type": "string"}, "description": "Bone renames in 3D bone tracks, old -> new."},
			"bone_pattern": host._str("Regex applied to bone names in bone tracks, e.g. \"^mixamorig[:_]\"."),
			"bone_replacement": host._str("Replacement for bone_pattern (default empty)."),
			"remove_missing_tracks": host._bool("Remove tracks whose node, bone or property does not exist (needs a scene source).", false),
			"remove_tracks_matching": host._str("Remove tracks whose path matches this regex."),
			"loop_mode": {"type": "string", "enum": ["none", "linear", "pingpong"], "description": "Set the loop mode."},
			"length": {"type": "number", "description": "Set the length in seconds."},
			"speed": {"type": "number", "description": "Playback speed factor baked into the keys (2 = twice as fast; scales key times and length)."},
			"copy_to": host._str("Copy the animation to this library of the same player (created if missing) or to a res://...tres AnimationLibrary (created if missing)."),
			"move": host._bool("With copy_to: remove it from the original library (a move).", false),
			"new_name": host._str("With copy_to: name in the target library (default: same name)."),
			"overwrite": host._bool("With copy_to: replace an existing animation of that name.", false),
			"dry_run": host._bool("Only report what would change.", false),
		}, ["animation"]),
		func(a): return _tool_edit(a), false, "animation")
	host._set_safe_fn("godot_animation_edit", func(a): return bool(a.get("dry_run", false)))

	var import_props := {
		"model": host._str("res:// path of the imported model (.glb, .gltf, .fbx, .blend, .dae)."),
		"action": {"type": "string", "enum": ["list", "apply", "extract", "remove"], "default": "list",
			"description": "list: show the animation names (and a preview when rules are given). apply: write a post-import script that renames them on every import, hook it into the model's import settings and reimport. extract: save renamed copies to an AnimationLibrary .tres. remove: unhook and trash the generated script."},
		"script_path": host._str("apply: where to write the post-import script (default: next to the model, <name>_anim_names.gd)."),
		"output": host._str("extract: AnimationLibrary path (default: next to the model, <name>_animations.tres)."),
		"replace_existing": host._bool("apply: replace an import script that was not generated by AI Studio.", false),
	}
	import_props.merge(rule_props)
	host._add("godot_import_animation_names",
		"Fix animation names that come from an imported model (\"mixamo.com\", \"Armature|Take 001\", \"CharacterArmature|Run\" ...). Renaming them in the scene does not stick because every reimport restores them, so this writes a small EditorScenePostImport script with your renames, hooks it into the model's import settings and reimports; or extracts renamed copies into an AnimationLibrary.",
		host._obj(import_props, ["model"]),
		func(a): return _tool_import_names(a), false, "animation")
	host._set_safe_fn("godot_import_animation_names", func(a): return String(a.get("action", "list")) == "list")

	host._add("godot_run_editor_script",
		"Run a one-off GDScript inside the editor for anything the other tools cannot do (batch edits, editor APIs, custom checks). Give the body of a function (it runs as func run(), may use await and should 'return' a result) or a full script that defines func run(). EditorInterface and every engine API are available; prints, errors and the return value come back. There is no sandbox and no timeout, so the user always has to approve it: keep it short, avoid infinite loops, and never touch res://addons/ai_studio.",
		host._obj({
			"code": host._str("GDScript: a function body (indented or not) or a script with func run()."),
		}, ["code"]),
		func(a): return await _tool_run_script(a), false, "editor")
	host.always_confirm("godot_run_editor_script")

	host._add("godot_editor_log",
		"Read the editor's messages: errors and warnings (with file and line) from the editor and from the debugger's Errors tab of the running/last game, the plain log, or the text of the Output panel (which also shows the game's print output). Use it after changing scripts or scenes, or when something silently does not work.",
		host._obj({
			"source": {"type": "string", "enum": ["errors", "all", "output", "debugger"], "default": "errors",
				"description": "errors: editor errors/warnings + debugger errors; all: every editor log entry incl. prints; output: the Output panel text; debugger: only the debugger's Errors tab."},
			"limit": host._int("Maximum entries/lines (newest).", 50),
			"contains": host._str("Only entries containing this text (case-insensitive)."),
			"since_id": host._int("Only editor log entries with a larger id (ids are shown in the output).", 0),
			"clear": host._bool("Clear the collected editor log after reading.", false),
		}),
		func(a): return _tool_editor_log(a), true, "editor")


# ---------------------------------------------------------------------------
# shared helpers
# ---------------------------------------------------------------------------

func _editor() -> bool:
	return AIStudioEditorEnv.available()


func _res_path(raw: Variant) -> String:
	var p := String(raw if raw != null else "").strip_edges().replace("\\", "/")
	if p.is_empty():
		return p
	if p.begins_with("uid://"):
		var id := ResourceUID.text_to_id(p)
		if id != ResourceUID.INVALID_ID and ResourceUID.has_id(id):
			return ResourceUID.get_id_path(id)
		return p
	if not p.begins_with("res://"):
		p = "res://" + p.trim_prefix("/")
	return p


static func _dict(v: Variant) -> Dictionary:
	if typeof(v) == TYPE_DICTIONARY:
		return v
	if typeof(v) == TYPE_STRING and String(v).strip_edges().begins_with("{"):
		var json := JSON.new()
		if json.parse(String(v)) == OK and typeof(json.data) == TYPE_DICTIONARY:
			return json.data
	return {}


static func _strings(v: Variant) -> PackedStringArray:
	var out := PackedStringArray()
	if typeof(v) == TYPE_ARRAY or typeof(v) == TYPE_PACKED_STRING_ARRAY:
		for x in v:
			out.append(String(x))
	elif typeof(v) == TYPE_STRING and not String(v).is_empty():
		for x in String(v).split(",", false):
			out.append(x.strip_edges())
	return out


func _rules(args: Dictionary) -> Dictionary:
	var renames := {}
	var raw := _dict(args.get("renames", {}))
	for k in raw.keys():
		renames[String(k)] = String(raw[k])
	var pattern := String(args.get("pattern", ""))
	if not pattern.is_empty():
		var re := RegEx.new()
		if re.compile(pattern) != OK:
			return {"ok": false, "error": "Invalid regex in 'pattern': " + pattern}
	return {"ok": true, "renames": renames, "pattern": pattern,
		"replacement": String(args.get("replacement", "")), "cleanup": String(args.get("cleanup", "none"))}


func _new_name(rules: Dictionary, anim_name: String, library: String = "") -> String:
	return AIStudioAnimNameRules.compute(anim_name, rules["renames"], rules["pattern"], rules["replacement"],
		rules["cleanup"], library)


static func _full(library: String, anim_name: String) -> String:
	return anim_name if library.is_empty() else library + "/" + anim_name


## Runs `steps` in order; each step is [object, method, args] or
## ["set", object, property, value]. One do-batch and one undo-batch per
## action keeps the order under our control.
func _batch(steps: Array) -> void:
	for s in steps:
		if s.size() == 4 and typeof(s[0]) == TYPE_STRING and s[0] == "set":
			if is_instance_valid(s[1]):
				(s[1] as Object).set(s[2], s[3])
		elif is_instance_valid(s[0]):
			(s[0] as Object).callv(String(s[1]), s[2])


func _commit(ctx: Dictionary, action: String, do_steps: Array, undo_steps: Array) -> void:
	if do_steps.is_empty():
		return
	if String(ctx["mode"]) == "edited":
		var ur := EditorInterface.get_editor_undo_redo()
		ur.create_action(action, UndoRedo.MERGE_DISABLE, ctx["root"])
		ur.add_do_method(self, "_batch", do_steps)
		var reversed := undo_steps.duplicate()
		reversed.reverse()
		ur.add_undo_method(self, "_batch", reversed)
		ur.commit_action(true)
	else:
		_batch(do_steps)


# ---------------------------------------------------------------------------
# opening a source
# ---------------------------------------------------------------------------

## ctx: {ok, error, mode: "edited" | "file" | "resource", root, res, path, label, reopen, saves}
func _open_ctx(raw: Variant) -> Dictionary:
	var s := String(raw if raw != null else "").strip_edges()
	var edited: Node = EditorInterface.get_edited_scene_root() if _editor() else null
	if s.is_empty():
		if edited == null:
			return {"ok": false, "error": "No scene is open in the editor; pass 'source' (a .tscn, or an AnimationLibrary / SpriteFrames .tres)."}
		return _edited_ctx(edited)
	s = _res_path(s)
	var chk: Dictionary = host._validate_project_path(s, true)
	if not bool(chk["ok"]):
		return {"ok": false, "error": chk["error"]}
	if edited != null and s == edited.scene_file_path:
		return _edited_ctx(edited)
	var ext := s.get_extension().to_lower()
	if ext in MODEL_EXTS:
		return {"ok": false, "error": "%s is an imported model: its animation names come from the file and every reimport restores them. Use godot_import_animation_names (action=apply) instead." % s}
	if not FileAccess.file_exists(s):
		return {"ok": false, "error": "Not found: " + s}
	if ext == "tscn" or ext == "scn":
		var reopen := false
		if _editor() and Array(EditorInterface.get_open_scenes()).has(s):
			if Array(EditorInterface.get_unsaved_scenes()).has(s):
				return {"ok": false, "error": "%s is open in the editor with unsaved changes. Save it first (godot_save_scenes), or switch to it and omit 'source'." % s}
			reopen = true
		var packed = ResourceLoader.load(s, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE)
		if not (packed is PackedScene):
			return {"ok": false, "error": "Could not load scene: " + s}
		var root: Node = (packed as PackedScene).instantiate(PackedScene.GEN_EDIT_STATE_MAIN)
		if root == null:
			return {"ok": false, "error": "Could not instantiate scene: " + s}
		return {"ok": true, "error": "", "mode": "file", "root": root, "res": null, "path": s, "label": s,
			"reopen": reopen, "saves": {}}
	var res = ResourceLoader.load(s)
	if res is AnimationLibrary or res is SpriteFrames or res is Animation:
		return {"ok": true, "error": "", "mode": "resource", "root": null, "res": res, "path": s, "label": s,
			"reopen": false, "saves": {}}
	return {"ok": false, "error": "%s is a %s; expected a scene, AnimationLibrary, SpriteFrames or Animation." % [s, res.get_class() if res != null else "file Godot cannot load"]}


func _edited_ctx(edited: Node) -> Dictionary:
	return {"ok": true, "error": "", "mode": "edited", "root": edited, "res": null,
		"path": edited.scene_file_path, "label": "(edited scene) " + (edited.scene_file_path if not edited.scene_file_path.is_empty() else String(edited.name)),
		"reopen": false, "saves": {}}


## Saves what changed and releases the instance. Returns an error text or "".
func _close_ctx(ctx: Dictionary, save: bool) -> String:
	var problem := ""
	var mode := String(ctx.get("mode", ""))
	if save:
		for p in ctx["saves"].keys():
			var err := ResourceSaver.save(ctx["saves"][p], p)
			if err != OK:
				problem += "Could not save %s (%s). " % [p, error_string(err)]
			elif _editor():
				EditorInterface.get_resource_filesystem().update_file(p)
	if mode == "file":
		var root: Node = ctx["root"]
		if save:
			var packed := PackedScene.new()
			var err := packed.pack(root)
			if err == OK:
				err = ResourceSaver.save(packed, ctx["path"])
			if err != OK:
				problem += "Could not save %s (%s). " % [ctx["path"], error_string(err)]
			elif _editor():
				EditorInterface.get_resource_filesystem().update_file(ctx["path"])
		if is_instance_valid(root):
			root.free()
		if save and problem.is_empty() and bool(ctx.get("reopen", false)) and _editor():
			EditorInterface.reload_scene_from_path(ctx["path"])
	elif mode == "resource" and save:
		var err := ResourceSaver.save(ctx["res"], ctx["path"])
		if err != OK:
			problem += "Could not save %s (%s). " % [ctx["path"], error_string(err)]
		elif _editor():
			EditorInterface.get_resource_filesystem().update_file(ctx["path"])
	return problem.strip_edges()


func _rel(ctx: Dictionary, node: Node) -> String:
	var root: Node = ctx["root"]
	return "." if node == root else String(root.get_path_to(node))


## Players, trees and animated sprites in the source, optionally one node.
## Each entry: {kind: "mixer" | "library" | "frames" | "animation", node, obj, label}
func _containers(ctx: Dictionary, node_filter: String) -> Array:
	var out: Array = []
	if String(ctx["mode"]) == "resource":
		var res = ctx["res"]
		var kind := "library" if res is AnimationLibrary else ("frames" if res is SpriteFrames else "animation")
		out.append({"kind": kind, "node": null, "obj": res, "label": ctx["path"]})
		return out
	var root: Node = ctx["root"]
	var nodes: Array = [root]
	nodes.append_array(root.find_children("*", "", true, false))
	var wanted := node_filter.strip_edges().trim_prefix("./")
	for n in nodes:
		var node: Node = n
		if not wanted.is_empty() and wanted != ".":
			var rel := _rel(ctx, node)
			if rel != wanted and String(node.name) != wanted and rel != wanted.trim_prefix(String(root.name) + "/"):
				continue
		elif wanted == "." and node != root:
			continue
		if node is AnimationMixer:
			out.append({"kind": "mixer", "node": node, "obj": node, "label": _rel(ctx, node)})
		elif (node is AnimatedSprite2D or node is AnimatedSprite3D) and node.get("sprite_frames") != null:
			out.append({"kind": "frames", "node": node, "obj": node.get("sprite_frames"), "label": _rel(ctx, node)})
	return out


## Where a resource is stored: embedded (saved with the scene), file (its own
## .tres/.res), other_scene (belongs to another .tscn) or imported.
func _origin(ctx: Dictionary, res: Resource) -> Dictionary:
	var rp := res.resource_path
	if rp.is_empty():
		return {"kind": "embedded", "path": ""}
	var base := rp.get_slice("::", 0)
	var ext := base.get_extension().to_lower()
	var scene_path := String(ctx["path"]) if String(ctx["mode"]) != "resource" else ""
	if String(ctx["mode"]) == "resource" and base == String(ctx["path"]):
		return {"kind": "file", "path": base, "self": true}
	if not scene_path.is_empty() and base == scene_path:
		return {"kind": "embedded", "path": ""}
	if ext in MODEL_EXTS:
		return {"kind": "imported", "path": base}
	if ext == "tscn" or ext == "scn":
		return {"kind": "other_scene", "path": base}
	return {"kind": "file", "path": base}


## Error text when a resource cannot be changed from here; records external
## files that must be saved afterwards.
func _writable(ctx: Dictionary, res: Resource, what: String) -> String:
	var o := _origin(ctx, res)
	match String(o["kind"]):
		"imported":
			return "%s comes from the imported model %s; every reimport restores it. Use godot_import_animation_names on %s." % [what, o["path"], o["path"]]
		"other_scene":
			return "%s is stored in %s. Run the tool again with source=%s." % [what, o["path"], o["path"]]
		"file":
			if bool(o.get("self", false)):
				return ""
			var chk: Dictionary = host._validate_project_path(String(o["path"]), true)
			if not bool(chk["ok"]):
				return String(chk["error"])
			var owner_res = ResourceLoader.load(String(o["path"]))
			if owner_res == null:
				return "Could not load %s to save it." % o["path"]
			ctx["saves"][String(o["path"])] = owner_res
	return ""


## Error text when the node's own properties (its library list) live in
## another scene.
func _node_writable(ctx: Dictionary, node: Node) -> String:
	var root: Node = ctx["root"]
	if node == root or node.owner == root:
		return ""
	var p := node.get_parent()
	while p != null and p != root:
		if not p.scene_file_path.is_empty():
			return "%s belongs to the instanced scene %s. Run the tool again with source=%s." % [_rel(ctx, node), p.scene_file_path, p.scene_file_path]
		p = p.get_parent()
	return "%s is not owned by this scene." % _rel(ctx, node)


static func _libraries(c: Dictionary) -> Array:
	var out: Array = []
	if String(c["kind"]) == "mixer":
		var mixer: AnimationMixer = c["node"]
		for ln in mixer.get_animation_library_list():
			var lib := mixer.get_animation_library(ln)
			if lib != null:
				out.append([String(ln), lib])
	elif String(c["kind"]) == "library":
		out.append(["", c["obj"]])
	return out


## AnimationNodeAnimation nodes under an AnimationTree root.
func _anim_nodes(node: AnimationNode, out: Array, seen: Dictionary) -> void:
	if node == null or seen.has(node.get_instance_id()):
		return
	seen[node.get_instance_id()] = true
	if node is AnimationNodeAnimation:
		out.append(node)
	elif node is AnimationNodeStateMachine:
		var sm := node as AnimationNodeStateMachine
		for n in sm.get_node_list():
			_anim_nodes(sm.get_node(n), out, seen)
	elif node is AnimationNodeBlendTree:
		var bt := node as AnimationNodeBlendTree
		for n in bt.get_node_list():
			_anim_nodes(bt.get_node(n), out, seen)
	elif node is AnimationNodeBlendSpace1D:
		var b1 := node as AnimationNodeBlendSpace1D
		for i in b1.get_blend_point_count():
			_anim_nodes(b1.get_blend_point_node(i), out, seen)
	elif node is AnimationNodeBlendSpace2D:
		var b2 := node as AnimationNodeBlendSpace2D
		for i in b2.get_blend_point_count():
			_anim_nodes(b2.get_blend_point_node(i), out, seen)


## Property fixes in the scene for renamed full names of `mixer`:
## [[object, property, old, new]], plus notes for things that could not change.
func _scene_fixes(ctx: Dictionary, mixer: AnimationMixer, full_map: Dictionary, notes: PackedStringArray) -> Array:
	var fixes: Array = []
	if full_map.is_empty():
		return fixes
	if mixer is AnimationPlayer:
		for prop in ["autoplay", "assigned_animation"]:
			var cur := String(mixer.get(prop))
			if full_map.has(cur):
				fixes.append([mixer, prop, cur, full_map[cur]])
	var root: Node = ctx["root"]
	var trees: Array = root.find_children("*", "AnimationTree", true, false)
	if root is AnimationTree:
		trees.append(root)
	for t in trees:
		var tree: AnimationTree = t
		var target: Node = tree if tree.anim_player.is_empty() else tree.get_node_or_null(tree.anim_player)
		if target != mixer or tree.tree_root == null:
			continue
		var found: Array = []
		_anim_nodes(tree.tree_root, found, {})
		var blocked := ""
		for an in found:
			var anode: AnimationNodeAnimation = an
			var cur := String(anode.animation)
			if not full_map.has(cur):
				continue
			if blocked.is_empty():
				blocked = _writable(ctx, tree.tree_root, "The AnimationTree %s" % _rel(ctx, tree))
				if not blocked.is_empty():
					notes.append("Not updated: " + blocked)
					break
			fixes.append([anode, "animation", cur, full_map[cur]])
	return fixes


# ---------------------------------------------------------------------------
# godot_animation_rename
# ---------------------------------------------------------------------------

func _tool_rename(args: Dictionary) -> Dictionary:
	var rules := _rules(args)
	if not bool(rules["ok"]):
		return host._err(rules["error"])
	if (rules["renames"] as Dictionary).is_empty() and String(rules["pattern"]).is_empty() and String(rules["cleanup"]) == "none":
		return host._err("Nothing to do: give 'renames', 'cleanup' or 'pattern'.")
	var ctx := _open_ctx(args.get("source", ""))
	if not bool(ctx["ok"]):
		return host._err(ctx["error"])
	var containers := _containers(ctx, String(args.get("node_path", "")))
	if containers.is_empty():
		_close_ctx(ctx, false)
		return host._err("No AnimationPlayer, AnimationTree, AnimationLibrary or AnimatedSprite found in %s%s." % [
			ctx["label"], "" if String(args.get("node_path", "")).is_empty() else " at " + String(args["node_path"])])
	var target := String(args.get("target", "animations"))
	var lib_filter_on := args.has("library") and args["library"] != null
	var lib_filter := String(args.get("library", "")) if lib_filter_on else ""
	var dry := bool(args.get("dry_run", false))
	var update_refs := bool(args.get("update_references", true))

	var lines := PackedStringArray()
	var problems := PackedStringArray()
	var notes := PackedStringArray()
	var do_steps: Array = []
	var undo_steps: Array = []
	var global_map := {}   # full old -> full new, for project references
	var done_objs := {}
	var count := 0
	var any_library := String(ctx["mode"]) == "resource" and String(containers[0]["kind"]) == "library"

	for c in containers:
		var kind := String(c["kind"])
		if kind == "animation":
			_close_ctx(ctx, false)
			return host._err("%s is a single Animation; its name is the key in a library. Rename it in the AnimationLibrary or scene that holds it." % ctx["path"])
		if kind == "frames":
			if target == "libraries":
				continue
			var frames: SpriteFrames = c["obj"]
			if done_objs.has(frames.get_instance_id()):
				continue
			done_objs[frames.get_instance_id()] = true
			var plan := _plan_names(rules, frames.get_animation_names(), "", frames.has_animation, problems, c["label"])
			if plan.is_empty():
				continue
			var blocked := _writable(ctx, frames, "SpriteFrames of " + String(c["label"]))
			if not blocked.is_empty():
				problems.append(blocked)
				continue
			var fixes: Array = []
			if String(ctx["mode"]) != "resource":
				for n in ([ctx["root"]] + (ctx["root"] as Node).find_children("*", "", true, false)):
					if (n is AnimatedSprite2D or n is AnimatedSprite3D) and n.get("sprite_frames") == frames:
						for prop in ["animation", "autoplay"]:
							var cur := String(n.get(prop))
							if plan.has(cur):
								fixes.append([n, prop, cur, plan[cur]])
			for old in plan.keys():
				lines.append("%s  SpriteFrames  %s -> %s" % [c["label"], old, plan[old]])
				do_steps.append([frames, "rename_animation", [old, plan[old]]])
				undo_steps.append([frames, "rename_animation", [plan[old], old]])
				global_map[old] = plan[old]
				count += 1
			_add_fixes(fixes, do_steps, undo_steps, lines)
			continue

		# mixers and libraries
		var mixer: AnimationMixer = c["node"] if kind == "mixer" else null
		var full_map := {}
		if target == "libraries":
			if mixer == null:
				problems.append("%s is a library resource; its key is set by the players that use it." % c["label"])
				continue
			var keys := PackedStringArray()
			for pair in _libraries(c):
				if lib_filter_on and pair[0] != lib_filter:
					continue
				keys.append(pair[0])
			var plan := _plan_names(rules, keys, "", mixer.has_animation_library, problems, c["label"] + " libraries")
			if plan.is_empty():
				continue
			var blocked := _node_writable(ctx, mixer)
			if not blocked.is_empty():
				problems.append(blocked)
				continue
			for old in plan.keys():
				lines.append("%s  library  \"%s\" -> \"%s\"" % [c["label"], old, plan[old]])
				do_steps.append([mixer, "rename_animation_library", [old, plan[old]]])
				undo_steps.append([mixer, "rename_animation_library", [plan[old], old]])
				for a in mixer.get_animation_library(old).get_animation_list():
					full_map[_full(old, String(a))] = _full(plan[old], String(a))
				count += 1
		else:
			for pair in _libraries(c):
				var ln := String(pair[0])
				var lib: AnimationLibrary = pair[1]
				if lib_filter_on and ln != lib_filter:
					continue
				var plan: Dictionary
				if done_objs.has(lib.get_instance_id()):
					plan = done_objs[lib.get_instance_id()]
				else:
					plan = _plan_names(rules, lib.get_animation_list(), ln, lib.has_animation, problems, "%s [%s]" % [c["label"], ln])
					if not plan.is_empty():
						var blocked := _writable(ctx, lib, "Library \"%s\" of %s" % [ln, c["label"]])
						if not blocked.is_empty():
							problems.append(blocked)
							plan = {}
					done_objs[lib.get_instance_id()] = plan
					for old in plan.keys():
						lines.append("%s  [%s]  %s -> %s" % [c["label"], ln, old, plan[old]])
						do_steps.append([lib, "rename_animation", [old, plan[old]]])
						undo_steps.append([lib, "rename_animation", [plan[old], old]])
						count += 1
				for old in plan.keys():
					full_map[_full(ln, old)] = _full(ln, plan[old])
		if mixer != null and update_refs:
			_add_fixes(_scene_fixes(ctx, mixer, full_map, notes), do_steps, undo_steps, lines)
		global_map.merge(full_map, true)

	if count == 0:
		_close_ctx(ctx, false)
		var why := "No names change with these rules." if problems.is_empty() else "Nothing renamed."
		return host._err(why + ("\n" + "\n".join(problems) if not problems.is_empty() else ""))

	var header := "%s %d name(s) in %s:" % ["Would rename" if dry else "Renamed", count, ctx["label"]]
	var out_lines := PackedStringArray([header])
	out_lines.append_array(lines)
	if not problems.is_empty():
		out_lines.append("Skipped:")
		for p in problems:
			out_lines.append("  " + p)
	out_lines.append_array(notes)

	var exclude := {}
	if not String(ctx["path"]).is_empty():
		exclude[String(ctx["path"])] = true
	if dry:
		_close_ctx(ctx, false)
		if update_refs:
			var refs := _scan_refs(global_map.keys(), any_library, exclude)
			out_lines.append(_format_refs(refs, "Project references that would be updated (use) or need a look (maybe):"))
		out_lines.append("Dry run: nothing was changed.")
		return host._ok("\n".join(out_lines))

	_commit(ctx, "AI Studio: rename animations", do_steps, undo_steps)
	for p in ctx["saves"].keys():
		exclude[p] = true
	var save_problem := _close_ctx(ctx, true)
	if not save_problem.is_empty():
		out_lines.append("WARNING: " + save_problem)
	if String(ctx["mode"]) == "edited":
		out_lines.append("Changed in the open scene (Ctrl+Z undoes it); save with godot_save_scenes.")
	if update_refs:
		var refs := _scan_refs(global_map.keys(), any_library, exclude)
		if refs.is_empty():
			out_lines.append("No other references to the old names in the project.")
		else:
			var applied := _apply_refs(refs, global_map, any_library, false)
			out_lines.append(String(applied["text"]))
	return host._ok("\n".join(out_lines))


## old -> new for names that change, validated against `exists`.
func _plan_names(rules: Dictionary, names: Variant, library: String, exists: Callable,
		problems: PackedStringArray, label: String) -> Dictionary:
	var plan := {}
	var taken := {}
	for n in names:
		var old := String(n)
		var new_name := _new_name(rules, old, library)
		if new_name == old:
			continue
		if not AIStudioAnimNameRules.is_valid_name(new_name):
			problems.append("%s: \"%s\" -> \"%s\" is not a valid name (empty or contains / : , [)." % [label, old, new_name])
			continue
		if bool(exists.call(StringName(new_name))) or taken.has(new_name):
			problems.append("%s: \"%s\" -> \"%s\" clashes with an existing name." % [label, old, new_name])
			continue
		taken[new_name] = true
		plan[old] = new_name
	return plan


func _add_fixes(fixes: Array, do_steps: Array, undo_steps: Array, lines: PackedStringArray) -> void:
	for f in fixes:
		do_steps.append(["set", f[0], f[1], StringName(f[3]) if typeof(f[0].get(f[1])) == TYPE_STRING_NAME else f[3]])
		undo_steps.append(["set", f[0], f[1], f[0].get(f[1])])
		var who: String = String(f[0].name) if f[0] is Node else f[0].get_class()
		lines.append("  also %s.%s: %s -> %s" % [who, f[1], f[2], f[3]])


# ---------------------------------------------------------------------------
# references
# ---------------------------------------------------------------------------

func _collect_ref_files(path: String, out: PackedStringArray) -> void:
	var dir := DirAccess.open(path)
	if dir == null:
		return
	dir.list_dir_begin()
	var name := dir.get_next()
	while not name.is_empty():
		var full := path.path_join(name)
		if dir.current_is_dir():
			# Third-party addons are never rewritten (and ours must not be).
			if not name.begins_with(".") and full != "res://addons":
				_collect_ref_files(full, out)
		elif name.get_extension().to_lower() in REF_EXTS:
			out.append(full)
		name = dir.get_next()
	dir.list_dir_end()


func _match_key(content: String, keys: Dictionary, any_library: bool) -> String:
	if keys.has(content):
		return content
	if any_library:
		var slash := content.find("/")
		if slash > 0 and keys.has(content.substr(slash + 1)):
			return content.substr(slash + 1)
	return ""


## [{path, line, text, kind: use | maybe | definition | state, key}]
func _scan_refs(names: Array, any_library: bool, exclude: Dictionary) -> Array:
	var out: Array = []
	if names.is_empty():
		return out
	var keys := {}
	for n in names:
		keys[String(n)] = true
	var files := PackedStringArray()
	_collect_ref_files("res://", files)
	for path in files:
		if exclude.has(path) or out.size() >= MAX_REFS:
			continue
		var f := FileAccess.open(path, FileAccess.READ)
		if f == null or f.get_length() > MAX_REF_FILE_BYTES:
			continue
		var text := f.get_as_text()
		f = null
		var hit := false
		for k in keys.keys():
			if text.contains(String(k)):
				hit = true
				break
		if not hit:
			continue
		var is_script := path.get_extension() in ["gd", "cs"]
		var lines := text.split("\n")
		for i in lines.size():
			var line: String = lines[i]
			for m in _literal_re.search_all(line):
				var content := m.get_string(2) if m.get_start(2) >= 0 else m.get_string(3)
				var key := _match_key(content, keys, any_library)
				if key.is_empty():
					continue
				out.append({"path": path, "line": i + 1, "text": line.strip_edges().left(160),
					"kind": _classify(line, is_script), "key": key})
				break
	return out


func _classify(line: String, is_script: bool) -> String:
	if is_script:
		var code := line.split("#", true, 1)[0] if not line.strip_edges().begins_with("//") else ""
		return "use" if _use_re.search(code) != null else "maybe"
	if _prop_re.search(line) != null:
		return "use"
	if _state_re.search(line) != null:
		return "state"
	if _def_re.search(line) != null:
		return "definition"
	return "maybe"


func _format_refs(refs: Array, title: String) -> String:
	if refs.is_empty():
		return title + " none."
	var lines := PackedStringArray([title])
	var counts := {}
	for r in refs:
		counts[r["kind"]] = int(counts.get(r["kind"], 0)) + 1
		lines.append("  %-10s %s:%d  %s" % [r["kind"], r["path"], r["line"], r["text"]])
	var summary := PackedStringArray()
	for k in counts.keys():
		summary.append("%d %s" % [counts[k], k])
	lines.append("  (" + ", ".join(summary) + ("; stopped at %d)" % MAX_REFS if refs.size() >= MAX_REFS else ")"))
	return "\n".join(lines)


## Rewrites 'use' matches (and 'maybe' ones when asked) to the new names.
func _apply_refs(refs: Array, map: Dictionary, any_library: bool, include_possible: bool) -> Dictionary:
	# A name that is still defined somewhere else (another scene's own library,
	# a SpriteFrames resource...) makes its uses ambiguous: a scene that defines
	# it refers to its own animation, and a script cannot be attributed.
	var defined := {}
	for r in refs:
		if String(r["kind"]) == "definition":
			if not defined.has(r["key"]):
				defined[r["key"]] = {}
			defined[r["key"]][r["path"]] = true
	var by_file := {}
	var reported: Array = []
	var ambiguous := PackedStringArray()
	for r in refs:
		var kind := String(r["kind"])
		if kind == "use" or (kind == "maybe" and include_possible):
			var key := String(r["key"])
			if defined.has(key):
				var is_script := String(r["path"]).get_extension() in ["gd", "cs"]
				if is_script or (defined[key] as Dictionary).has(r["path"]):
					ambiguous.append("  %s:%d  %s  (\"%s\" is still defined in %s)" % [r["path"], r["line"], r["text"], key,
						", ".join(PackedStringArray((defined[key] as Dictionary).keys()))])
					continue
			if not by_file.has(r["path"]):
				by_file[r["path"]] = {"refs": [], "keys": {}}
			by_file[r["path"]]["refs"].append(r)
			by_file[r["path"]]["keys"][key] = true
		else:
			reported.append(r)
	var changed := PackedStringArray()
	var skipped := PackedStringArray()
	var replaced := 0
	var backup_dir := "user://ai_studio/backups/refs_%d" % int(Time.get_unix_time_from_system())
	var open_scenes: Array = Array(EditorInterface.get_open_scenes()) if _editor() else []
	var unsaved: Array = Array(EditorInterface.get_unsaved_scenes()) if _editor() else []
	for path in by_file.keys():
		var chk: Dictionary = host._validate_project_path(path, true)
		if not bool(chk["ok"]):
			skipped.append("%s (%s)" % [path, chk["error"]])
			continue
		if unsaved.has(path):
			skipped.append("%s (open with unsaved changes; save it and run godot_animation_find_references again)" % path)
			continue
		var text := FileAccess.get_file_as_string(path)
		var lines := text.split("\n")
		var n_here := 0
		var allowed: Dictionary = by_file[path]["keys"]
		for r in by_file[path]["refs"]:
			var idx := int(r["line"]) - 1
			var line: String = lines[idx]
			var matches := _literal_re.search_all(line)
			matches.reverse()
			for m in matches:
				var group := 2 if m.get_start(2) >= 0 else 3
				var content := m.get_string(group)
				var key := _match_key(content, map, any_library)
				if key.is_empty() or not allowed.has(key):
					continue
				var new_content := content.substr(0, content.length() - key.length()) + String(map[key])
				line = line.substr(0, m.get_start(group)) + new_content + line.substr(m.get_end(group))
				n_here += 1
			lines[idx] = line
		if n_here == 0:
			continue
		DirAccess.make_dir_recursive_absolute(backup_dir.path_join(path.trim_prefix("res://").get_base_dir()))
		var bak := FileAccess.open(backup_dir.path_join(path.trim_prefix("res://")), FileAccess.WRITE)
		if bak != null:
			bak.store_string(text)
			bak = null
		var f := FileAccess.open(path, FileAccess.WRITE)
		if f == null:
			skipped.append("%s (cannot write)" % path)
			continue
		f.store_string("\n".join(lines))
		f = null
		replaced += n_here
		changed.append("%s (%d)" % [path, n_here])
		if _editor():
			EditorInterface.get_resource_filesystem().update_file(path)
			if open_scenes.has(path):
				EditorInterface.reload_scene_from_path(path)
	var out := PackedStringArray()
	out.append("References updated: %d in %d file(s)%s" % [replaced, changed.size(), ":" if not changed.is_empty() else "."])
	for c in changed:
		out.append("  " + c)
	if not changed.is_empty():
		out.append("  Backups: " + ProjectSettings.globalize_path(backup_dir) + ". Scripts open in the script editor may ask to reload from disk.")
	for s in skipped:
		out.append("  skipped " + s)
	if not ambiguous.is_empty():
		out.append("Not changed because the old name is still defined elsewhere (these may refer to that other animation; fix by hand or rename it there too):")
		out.append_array(ambiguous)
	var left := 0
	for r in refs:
		if String(r["kind"]) == "maybe" and not include_possible:
			left += 1
	if left > 0 or not reported.is_empty():
		var rest: Array = []
		for r in refs:
			if not (String(r["kind"]) == "use" or (String(r["kind"]) == "maybe" and include_possible)):
				rest.append(r)
		out.append(_format_refs(rest, "Not changed (check these by hand; 'state' = state-machine state names, 'definition' = the name itself):"))
	return {"text": "\n".join(out), "replaced": replaced}


func _tool_find_references(args: Dictionary) -> Dictionary:
	var renames := _dict(args.get("renames", {}))
	var names := _strings(args.get("names", []))
	var map := {}
	for k in renames.keys():
		map[String(k)] = String(renames[k])
		if not names.has(String(k)):
			names.append(String(k))
	if names.is_empty():
		return host._err("Give 'names' to search for, or 'renames' (old -> new).")
	var any_library := bool(args.get("any_library", false))
	var refs := _scan_refs(Array(names), any_library, {})
	if not bool(args.get("apply", false)):
		return host._ok(_format_refs(refs, "References to %s:" % ", ".join(names)))
	if map.is_empty():
		return host._err("apply=true needs 'renames' (old -> new).")
	for k in map.keys():
		if not AIStudioAnimNameRules.is_valid_name(String(map[k]).get_slice("/", String(map[k]).count("/"))):
			return host._err("\"%s\" is not a valid animation name." % map[k])
	if refs.is_empty():
		return host._ok("No references to %s found." % ", ".join(names))
	var applied := _apply_refs(refs, map, any_library, bool(args.get("include_possible", false)))
	return host._ok(String(applied["text"]) + "\nThis only rewrote references; rename the animations themselves with godot_animation_rename (update_references=false).")


# ---------------------------------------------------------------------------
# godot_animation_edit
# ---------------------------------------------------------------------------

func _tool_edit(args: Dictionary) -> Dictionary:
	var wanted := String(args.get("animation", "")).strip_edges()
	if wanted.is_empty():
		return host._err("'animation' is required (a name, \"library/name\" or \"*\").")
	for key in ["bone_pattern", "remove_tracks_matching"]:
		var pat := String(args.get(key, ""))
		if not pat.is_empty():
			var re := RegEx.new()
			if re.compile(pat) != OK:
				return host._err("Invalid regex in %s: %s" % [key, pat])
	if args.has("speed") and float(args["speed"]) <= 0.0:
		return host._err("speed must be greater than 0.")
	if args.has("length") and float(args["length"]) <= 0.0:
		return host._err("length must be greater than 0.")
	var ctx := _open_ctx(args.get("source", ""))
	if not bool(ctx["ok"]):
		return host._err(ctx["error"])
	var dry := bool(args.get("dry_run", false))
	var lib_filter_on := args.has("library") and args["library"] != null
	var lib_filter := String(args.get("library", "")) if lib_filter_on else ""
	var containers := _containers(ctx, String(args.get("node_path", "")))

	# Single Animation resource: edit it and save the file.
	if String(ctx["mode"]) == "resource" and ctx["res"] is Animation:
		var anim: Animation = ctx["res"]
		var report := _edit_animation(anim if not dry else anim.duplicate(true), args, null)
		var text := "%s %s:\n%s" % ["Would change" if dry else "Changed", ctx["path"], "\n".join(report["lines"])]
		if args.has("copy_to"):
			text += "\ncopy_to is not available for a single Animation resource."
		if dry or int(report["count"]) == 0:
			_close_ctx(ctx, false)
			return host._ok(text + ("\nDry run: nothing was changed." if dry else ""))
		var problem := _close_ctx(ctx, true)
		return host._ok(text + ("\nWARNING: " + problem if not problem.is_empty() else ""))

	var targets: Array = []
	var available := PackedStringArray()
	var seen := {}
	for c in containers:
		for pair in _libraries(c):
			var ln := String(pair[0])
			var lib: AnimationLibrary = pair[1]
			if lib_filter_on and ln != lib_filter:
				continue
			for a in lib.get_animation_list():
				var an := String(a)
				var full := _full(ln, an)
				available.append("%s: %s" % [c["label"], full])
				if wanted != "*" and wanted != full and not (wanted == an and (lib_filter_on or ln.is_empty() or not wanted.contains("/"))):
					continue
				var id := "%d/%s" % [lib.get_instance_id(), an]
				if seen.has(id):
					continue
				seen[id] = true
				targets.append({"c": c, "ln": ln, "lib": lib, "name": an, "full": full})
	if targets.is_empty():
		_close_ctx(ctx, false)
		if available.is_empty():
			return host._err("No animations found in %s." % ctx["label"])
		return host._err("No animation '%s' in %s. Available:\n  %s" % [wanted, ctx["label"], "\n  ".join(available.slice(0, 80))])

	var lines := PackedStringArray()
	var problems := PackedStringArray()
	var do_steps: Array = []
	var undo_steps: Array = []
	var changed := 0
	var copy_to := String(args.get("copy_to", "")).strip_edges()
	var file_libs := {}   # res path -> AnimationLibrary to save (copy_to a .tres)
	var new_libs := {}    # "mixer id/key" -> AnimationLibrary created in this call

	for t in targets:
		var c: Dictionary = t["c"]
		var lib: AnimationLibrary = t["lib"]
		var anim: Animation = lib.get_animation(t["name"])
		var label := "%s: %s" % [c["label"], t["full"]]
		var own_file := not anim.resource_path.is_empty() and not anim.resource_path.contains("::")
		var blocked := ""
		var animated_root: Node = null
		if String(c["kind"]) == "mixer":
			var mixer: AnimationMixer = c["node"]
			animated_root = mixer.get_node_or_null(mixer.root_node)
		var work: Animation = anim.duplicate(true)
		var report := _edit_animation(work, args, animated_root)
		var edits := int(report["count"])
		if edits > 0:
			if own_file:
				blocked = _writable(ctx, anim, label)
			else:
				blocked = _writable(ctx, lib, "The library holding " + label)
			if not blocked.is_empty():
				problems.append(blocked)
				continue
			lines.append(label)
			for l in report["lines"]:
				lines.append("  " + String(l))
			if not dry:
				if own_file:
					# Stored in its own file: change that file (not undoable).
					_edit_animation(anim, args, animated_root)
					ctx["saves"][anim.resource_path] = anim
				else:
					do_steps.append([lib, "add_animation", [t["name"], work]])
					undo_steps.append([lib, "add_animation", [t["name"], anim]])
			changed += 1
		elif copy_to.is_empty():
			lines.append("%s: no changes (%s)" % [label, "; ".join(report["lines"]) if not (report["lines"] as Array).is_empty() else "nothing matched"])
		if copy_to.is_empty():
			continue
		# ---- copy / move ----
		var dest_name := String(args.get("new_name", "")).strip_edges()
		if dest_name.is_empty() or targets.size() > 1:
			dest_name = String(t["name"])
		if not AIStudioAnimNameRules.is_valid_name(dest_name):
			problems.append("\"%s\" is not a valid animation name." % dest_name)
			continue
		var copy: Animation = (work if edits > 0 else anim).duplicate(true)
		var dest: AnimationLibrary = null
		var dest_label := ""
		if copy_to.begins_with("res://") or copy_to.begins_with("uid://") or copy_to.ends_with(".tres") or copy_to.ends_with(".res"):
			var p := _res_path(copy_to)
			var chk: Dictionary = host._validate_project_path(p, true)
			if not bool(chk["ok"]):
				problems.append(String(chk["error"]))
				continue
			if not (p.ends_with(".tres") or p.ends_with(".res")):
				problems.append("copy_to must be a .tres/.res AnimationLibrary: " + p)
				continue
			if file_libs.has(p):
				dest = file_libs[p]
			elif FileAccess.file_exists(p):
				var loaded = ResourceLoader.load(p)
				if not (loaded is AnimationLibrary):
					problems.append("%s is not an AnimationLibrary." % p)
					continue
				dest = loaded
			else:
				dest = AnimationLibrary.new()
			file_libs[p] = dest
			dest_label = p
		else:
			if String(c["kind"]) != "mixer":
				problems.append("copy_to \"%s\": a library key needs an AnimationPlayer; use a res://...tres path here." % copy_to)
				continue
			var mixer: AnimationMixer = c["node"]
			if not AIStudioAnimNameRules.is_valid_name(copy_to):
				problems.append("\"%s\" is not a valid library name." % copy_to)
				continue
			var key := "%d/%s" % [mixer.get_instance_id(), copy_to]
			if new_libs.has(key):
				dest = new_libs[key]
			elif mixer.has_animation_library(copy_to):
				dest = mixer.get_animation_library(copy_to)
				var b := _writable(ctx, dest, "Library \"%s\"" % copy_to)
				if not b.is_empty():
					problems.append(b)
					continue
			else:
				var nb := _node_writable(ctx, mixer)
				if not nb.is_empty():
					problems.append(nb)
					continue
				dest = AnimationLibrary.new()
				new_libs[key] = dest
				do_steps.append([mixer, "add_animation_library", [copy_to, dest]])
				undo_steps.append([mixer, "remove_animation_library", [copy_to]])
			dest_label = "%s library \"%s\"" % [c["label"], copy_to]
		if dest == lib and dest_name == String(t["name"]):
			problems.append("%s: source and destination are the same." % label)
			continue
		var existing: Animation = dest.get_animation(dest_name) if dest.has_animation(dest_name) else null
		if existing != null and not bool(args.get("overwrite", false)):
			problems.append("%s already has \"%s\" (pass overwrite=true)." % [dest_label, dest_name])
			continue
		lines.append("%s -> %s as \"%s\"%s" % [label, dest_label, dest_name, " (moved)" if bool(args.get("move", false)) else ""])
		if file_libs.values().has(dest):
			if not dry:
				dest.add_animation(dest_name, copy)
		else:
			do_steps.append([dest, "add_animation", [dest_name, copy]])
			if existing != null:
				undo_steps.append([dest, "add_animation", [dest_name, existing]])
			else:
				undo_steps.append([dest, "remove_animation", [dest_name]])
		if bool(args.get("move", false)):
			var mb := _writable(ctx, lib, "The library holding " + label)
			if not mb.is_empty():
				problems.append("Copied but not removed: " + mb)
			else:
				do_steps.append([lib, "remove_animation", [t["name"]]])
				undo_steps.append([lib, "add_animation", [t["name"], anim]])
		changed += 1

	var out := PackedStringArray()
	out.append("%s %d animation(s) in %s:" % ["Would change" if dry else "Changed", changed, ctx["label"]])
	out.append_array(lines)
	if not problems.is_empty():
		out.append("Skipped:")
		for p in problems:
			out.append("  " + p)
	if dry or changed == 0:
		_close_ctx(ctx, false)
		if dry:
			out.append("Dry run: nothing was changed.")
		return host._ok("\n".join(out)) if changed > 0 or problems.is_empty() else host._err("\n".join(out))
	_commit(ctx, "AI Studio: edit animations", do_steps, undo_steps)
	for p in file_libs.keys():
		ctx["saves"][p] = file_libs[p]
	var problem := _close_ctx(ctx, true)
	if not problem.is_empty():
		out.append("WARNING: " + problem)
	if String(ctx["mode"]) == "edited":
		out.append("Changed in the open scene (Ctrl+Z undoes it); save with godot_save_scenes.")
	if not file_libs.is_empty():
		out.append("Saved: " + ", ".join(PackedStringArray(file_libs.keys())) + " (add it to an AnimationPlayer's libraries to use it).")
	return host._ok("\n".join(out))


## Applies the edit arguments to `anim`. Returns {count, lines}.
func _edit_animation(anim: Animation, args: Dictionary, animated_root: Node) -> Dictionary:
	var lines := PackedStringArray()
	var count := 0
	var from := String(args.get("path_prefix_from", "")).strip_edges().trim_suffix("/")
	var to := String(args.get("path_prefix_to", "")).strip_edges().trim_suffix("/")
	var bone_map := _dict(args.get("bone_renames", {}))
	var bone_re: RegEx = null
	if not String(args.get("bone_pattern", "")).is_empty():
		bone_re = RegEx.create_from_string(String(args["bone_pattern"]))
	var bone_repl := String(args.get("bone_replacement", ""))
	var n_paths := 0
	var n_bones := 0
	var examples := PackedStringArray()
	for t in anim.get_track_count():
		var p := String(anim.track_get_path(t))
		var np := p
		if not from.is_empty():
			if np == from:
				np = to if not to.is_empty() else "."
			elif np.begins_with(from + "/") or np.begins_with(from + ":"):
				var rest := np.substr(from.length())
				if to.is_empty():
					np = rest.trim_prefix("/") if rest.begins_with("/") else "." + rest
				else:
					np = to + rest
		if np != p:
			n_paths += 1
		var tt := anim.track_get_type(t)
		if (tt == Animation.TYPE_POSITION_3D or tt == Animation.TYPE_ROTATION_3D or tt == Animation.TYPE_SCALE_3D) \
				and np.contains(":") and (not bone_map.is_empty() or bone_re != null):
			var node_part := np.substr(0, np.find(":"))
			var bone := np.substr(np.find(":") + 1)
			var nb := String(bone_map.get(bone, bone))
			if bone_re != null:
				nb = bone_re.sub(nb, bone_repl, true)
			if nb != bone and not nb.is_empty():
				np = node_part + ":" + nb
				n_bones += 1
		if np != p:
			anim.track_set_path(t, NodePath(np))
			if examples.size() < 3:
				examples.append("%s -> %s" % [p, np])
	if n_paths > 0:
		lines.append("%d track path(s) re-prefixed" % n_paths)
	if n_bones > 0:
		lines.append("%d bone track(s) renamed" % n_bones)
	if not examples.is_empty():
		lines.append("e.g. " + "; ".join(examples))
	count += n_paths + n_bones

	var remove_re: RegEx = null
	if not String(args.get("remove_tracks_matching", "")).is_empty():
		remove_re = RegEx.create_from_string(String(args["remove_tracks_matching"]))
	var remove_missing := bool(args.get("remove_missing_tracks", false))
	if remove_missing and animated_root == null:
		lines.append("remove_missing_tracks skipped: needs a scene with the AnimationPlayer (its root node could not be resolved)")
		remove_missing = false
	var removed := PackedStringArray()
	for t in range(anim.get_track_count() - 1, -1, -1):
		var path := String(anim.track_get_path(t))
		if (remove_re != null and remove_re.search(path) != null) or (remove_missing and _track_missing(anim, t, animated_root)):
			anim.remove_track(t)
			removed.append(path)
	if not removed.is_empty():
		lines.append("%d track(s) removed: %s%s" % [removed.size(), ", ".join(removed.slice(0, 6)), " ..." if removed.size() > 6 else ""])
		count += removed.size()

	if args.has("loop_mode") and LOOP_MODES.has(String(args["loop_mode"])):
		var mode: int = LOOP_MODES[String(args["loop_mode"])]
		if anim.loop_mode != mode:
			anim.loop_mode = mode
			lines.append("loop mode -> " + String(args["loop_mode"]))
			count += 1
	if args.has("speed") and not is_equal_approx(float(args["speed"]), 1.0):
		var f := 1.0 / float(args["speed"])
		for t in anim.get_track_count():
			var n := anim.track_get_key_count(t)
			var order := range(n - 1, -1, -1) if f > 1.0 else range(n)
			for k in order:
				anim.track_set_key_time(t, k, anim.track_get_key_time(t, k) * f)
		anim.length = anim.length * f
		lines.append("speed x%s (length now %.3fs)" % [str(float(args["speed"])), anim.length])
		count += 1
	if args.has("length") and not is_equal_approx(float(args["length"]), anim.length):
		anim.length = float(args["length"])
		lines.append("length -> %.3fs" % anim.length)
		count += 1
	return {"count": count, "lines": lines}


func _track_missing(anim: Animation, t: int, root: Node) -> bool:
	var text := String(anim.track_get_path(t))
	var node_part := text
	var sub := ""
	var colon := text.find(":")
	if colon >= 0:
		node_part = text.substr(0, colon)
		sub = text.substr(colon + 1)
	var node := root.get_node_or_null(NodePath(node_part if not node_part.is_empty() else "."))
	if node == null:
		return true
	if sub.is_empty():
		return false
	var tt := anim.track_get_type(t)
	if node is Skeleton3D and (tt == Animation.TYPE_POSITION_3D or tt == Animation.TYPE_ROTATION_3D or tt == Animation.TYPE_SCALE_3D):
		return (node as Skeleton3D).find_bone(sub) < 0
	if tt == Animation.TYPE_BLEND_SHAPE:
		return not (node is MeshInstance3D) or (node as MeshInstance3D).find_blend_shape_by_name(sub) < 0
	var head := sub.get_slice(":", 0)
	return not (head in node)


# ---------------------------------------------------------------------------
# godot_import_animation_names
# ---------------------------------------------------------------------------

func _model_animations(model: String) -> Array:
	var out: Array = []
	var packed = ResourceLoader.load(model, "PackedScene", ResourceLoader.CACHE_MODE_IGNORE)
	if not (packed is PackedScene):
		return out
	var root: Node = (packed as PackedScene).instantiate()
	if root == null:
		return out
	var nodes: Array = [root]
	nodes.append_array(root.find_children("*", "AnimationMixer", true, false))
	for n in nodes:
		if not (n is AnimationMixer):
			continue
		var mixer: AnimationMixer = n
		for ln in mixer.get_animation_library_list():
			var lib := mixer.get_animation_library(ln)
			if lib == null:
				continue
			for a in lib.get_animation_list():
				out.append({"player": "." if mixer == root else String(root.get_path_to(mixer)), "library": String(ln),
					"name": String(a), "animation": lib.get_animation(a)})
	root.free()
	return out


func _tool_import_names(args: Dictionary) -> Dictionary:
	var model := _res_path(args.get("model", ""))
	var chk: Dictionary = host._validate_project_path(model, false)
	if not bool(chk["ok"]):
		return host._err(chk["error"])
	if not (model.get_extension().to_lower() in MODEL_EXTS):
		return host._err("%s is not an imported model (%s). For scenes and libraries use godot_animation_rename." % [model, ", ".join(MODEL_EXTS)])
	var import_path := model + ".import"
	if not FileAccess.file_exists(import_path):
		return host._err("%s has no .import file - is it imported? (Open the project in the editor once.)" % model)
	var action := String(args.get("action", "list"))
	var rules := _rules(args)
	if not bool(rules["ok"]):
		return host._err(rules["error"])
	var has_rules := not (rules["renames"] as Dictionary).is_empty() or not String(rules["pattern"]).is_empty() or String(rules["cleanup"]) != "none"
	var cfg := ConfigFile.new()
	if cfg.load(import_path) != OK:
		return host._err("Could not read " + import_path)
	var current_script := String(cfg.get_value("params", "import_script/path", ""))
	var ours := not current_script.is_empty() and FileAccess.file_exists(current_script) \
		and FileAccess.get_file_as_string(current_script).contains(GENERATED_MARK)
	var anims := _model_animations(model)

	match action:
		"list":
			var lines := PackedStringArray()
			lines.append("%s: %d animation(s)%s" % [model, anims.size(), "" if not anims.is_empty() else " (none, or the model failed to load)"])
			for a in anims:
				var line := "  %s  [%s]  %s  (%.2fs)" % [a["player"], a["library"], a["name"], (a["animation"] as Animation).length]
				if has_rules:
					var nn := _new_name(rules, a["name"], a["library"])
					if nn != a["name"]:
						line += "  -> " + nn + ("" if AIStudioAnimNameRules.is_valid_name(nn) else "  (INVALID)")
				lines.append(line)
			lines.append("Import script: %s" % (current_script + (" (generated by AI Studio)" if ours else "") if not current_script.is_empty() else "none"))
			return host._ok("\n".join(lines))
		"remove":
			if current_script.is_empty():
				return host._ok("%s has no import script." % model)
			if not ours:
				return host._err("%s uses %s, which was not generated by AI Studio; remove it in the import settings yourself." % [model, current_script])
			cfg.set_value("params", "import_script/path", "")
			if cfg.save(import_path) != OK:
				return host._err("Could not write " + import_path)
			OS.move_to_trash(ProjectSettings.globalize_path(current_script))
			var note := _reimport(model)
			return host._ok("Unhooked and trashed %s. %s" % [current_script, note])
		"extract":
			if anims.is_empty():
				return host._err("No animations in %s." % model)
			var out_path := _res_path(args.get("output", "")) if not String(args.get("output", "")).is_empty() \
				else model.get_basename() + "_animations.tres"
			var chk_out: Dictionary = host._validate_project_path(out_path, true)
			if not bool(chk_out["ok"]):
				return host._err(chk_out["error"])
			var lib := AnimationLibrary.new()
			var lines := PackedStringArray()
			for a in anims:
				var nn := _new_name(rules, a["name"], a["library"]) if has_rules else String(a["name"])
				if not AIStudioAnimNameRules.is_valid_name(nn) or lib.has_animation(nn):
					lines.append("  skipped %s -> %s (invalid or duplicate)" % [a["name"], nn])
					continue
				var copy: Animation = (a["animation"] as Animation).duplicate(true)
				copy.resource_name = nn
				lib.add_animation(nn, copy)
				lines.append("  %s -> %s" % [a["name"], nn] if nn != a["name"] else "  " + nn)
			var err := ResourceSaver.save(lib, out_path)
			if err != OK:
				return host._err("Could not save %s (%s)." % [out_path, error_string(err)])
			if _editor():
				EditorInterface.get_resource_filesystem().update_file(out_path)
			return host._ok("Saved %d animation(s) to %s:\n%s\nAdd it to an AnimationPlayer (Animation > Manage Animations > Load Library, or set it with godot_set_node_property) — it is independent of the model, so reimports do not change it." % [lib.get_animation_list().size(), out_path, "\n".join(lines)])
		"apply":
			if not has_rules:
				return host._err("apply needs 'renames', 'cleanup' or 'pattern'.")
			if not current_script.is_empty() and not ours and not bool(args.get("replace_existing", false)):
				return host._err("%s already uses the import script %s. Pass replace_existing=true to replace it, or add the renames to that script." % [model, current_script])
			var preview := PackedStringArray()
			var bad := PackedStringArray()
			var per_lib := {}
			for a in anims:
				var nn := _new_name(rules, a["name"], a["library"])
				if nn == a["name"]:
					continue
				var k := "%s|%s" % [a["player"], a["library"]]
				if not per_lib.has(k):
					per_lib[k] = {}
					for b in anims:
						if "%s|%s" % [b["player"], b["library"]] == k:
							per_lib[k][b["name"]] = true
				if not AIStudioAnimNameRules.is_valid_name(nn) or (per_lib[k] as Dictionary).has(nn):
					bad.append("%s -> %s (invalid or clashes; it will be left alone)" % [a["name"], nn])
					continue
				per_lib[k][nn] = true
				preview.append("%s -> %s" % [a["name"], nn])
			var script_path := _res_path(args.get("script_path", "")) if not String(args.get("script_path", "")).is_empty() \
				else (current_script if ours else model.get_basename() + "_anim_names.gd")
			var chk_script: Dictionary = host._validate_project_path(script_path, true)
			if not bool(chk_script["ok"]):
				return host._err(chk_script["error"])
			if not script_path.ends_with(".gd"):
				return host._err("script_path must end in .gd")
			var err := _write_text(script_path, _post_import_source(model, rules))
			if err != OK:
				return host._err("Could not write %s (%s)." % [script_path, error_string(err)])
			cfg.set_value("params", "import_script/path", script_path)
			if cfg.save(import_path) != OK:
				return host._err("Could not write " + import_path)
			var note := _reimport(model)
			var lines := PackedStringArray()
			lines.append("Wrote %s and set it as the import script of %s. %s" % [script_path, model, note])
			if preview.is_empty():
				lines.append("No current animation name changes with these rules (they still apply to future reimports).")
			else:
				lines.append("Renames: " + ", ".join(preview))
			for b in bad:
				lines.append("  " + b)
			if _editor():
				var after := PackedStringArray()
				for a in _model_animations(model):
					after.append(String(a["name"]) if String(a["library"]).is_empty() else "%s/%s" % [a["library"], a["name"]])
				lines.append("Names after reimport: " + ", ".join(after))
			if not preview.is_empty():
				var map := {}
				for p in preview:
					map[p.get_slice(" -> ", 0)] = p.get_slice(" -> ", 1)
				lines.append("Scripts or scenes that still use the old names: run godot_animation_find_references with renames=%s and apply=true." % JSON.stringify(map))
			return host._ok("\n".join(lines))
	return host._err("Unknown action: " + action)


func _reimport(model: String) -> String:
	if not _editor():
		return "Reimport it in the editor to apply."
	var fs := EditorInterface.get_resource_filesystem()
	fs.update_file(model)
	fs.reimport_files(PackedStringArray([model]))
	return "Reimported."


func _write_text(path: String, text: String) -> Error:
	var dir := path.get_base_dir()
	if not DirAccess.dir_exists_absolute(dir):
		DirAccess.make_dir_recursive_absolute(dir)
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		return FileAccess.get_open_error()
	f.store_string(text)
	f = null
	if _editor():
		EditorInterface.get_resource_filesystem().update_file(path)
	return OK


func _post_import_source(model: String, rules: Dictionary) -> String:
	var src := PackedStringArray()
	src.append("@tool")
	src.append("extends EditorScenePostImport")
	src.append("")
	src.append("## %s for %s." % [GENERATED_MARK, model])
	src.append("## Renames the model's animations on every import. To undo: clear Import Script")
	src.append("## in the model's import settings (or ask for action=remove) and delete this file.")
	src.append("")
	src.append("const RENAMES := " + var_to_str(rules["renames"]).replace("\n", " "))
	src.append("const PATTERN := " + var_to_str(String(rules["pattern"])))
	src.append("const REPLACEMENT := " + var_to_str(String(rules["replacement"])))
	src.append("const CLEANUP := " + var_to_str(String(rules["cleanup"])))
	src.append("")
	src.append("")
	src.append("func _post_import(scene: Node) -> Object:")
	src.append("\t_walk(scene)")
	src.append("\treturn scene")
	src.append("")
	src.append("")
	src.append("func _walk(node: Node) -> void:")
	src.append("\tif node is AnimationMixer:")
	src.append("\t\tvar mixer := node as AnimationMixer")
	src.append("\t\tfor lib_name in mixer.get_animation_library_list():")
	src.append("\t\t\tvar lib := mixer.get_animation_library(lib_name)")
	src.append("\t\t\tif lib == null:")
	src.append("\t\t\t\tcontinue")
	src.append("\t\t\tfor anim_name in lib.get_animation_list():")
	src.append("\t\t\t\tvar new_name := compute(String(anim_name), RENAMES, PATTERN, REPLACEMENT, CLEANUP, String(lib_name))")
	src.append("\t\t\t\tif new_name != String(anim_name) and is_valid_name(new_name) and not lib.has_animation(new_name):")
	src.append("\t\t\t\t\tlib.rename_animation(anim_name, new_name)")
	src.append("\t\t\t\t\tlib.get_animation(new_name).resource_name = new_name")
	src.append("\tfor child in node.get_children():")
	src.append("\t\t_walk(child)")
	src.append("")
	src.append("")
	src.append(AIStudioAnimNameRules.rules_source())
	src.append("")
	return "\n".join(src)


# ---------------------------------------------------------------------------
# godot_run_editor_script
# ---------------------------------------------------------------------------

class _Capture extends Logger:
	var mutex := Mutex.new()

	## The script has no file: its frames carry "" or a gdscript:// id.
	static func _is_own(path: String) -> bool:
		return path.is_empty() or path.begins_with("gdscript://")

	var output := PackedStringArray()
	var errors: Array = []

	func _log_message(message: String, error: bool) -> void:
		mutex.lock()
		output.append(("[stderr] " if error else "") + message.strip_edges(false, true))
		mutex.unlock()

	func _log_error(function: String, file: String, line: int, code: String, rationale: String,
			_editor_notify: bool, error_type: int, script_backtraces: Array[ScriptBacktrace]) -> void:
		var e := {"message": rationale if not rationale.is_empty() else code, "file": file, "line": line,
			"function": function, "warning": error_type == Logger.ERROR_TYPE_WARNING}
		var own := _is_own(file)
		for bt in script_backtraces:
			if bt != null and bt.get_frame_count() > 0:
				e["script_file"] = bt.get_frame_file(0)
				e["script_line"] = bt.get_frame_line(0)
				own = own or _is_own(String(e["script_file"]))
				break
		# Messages from elsewhere in the editor that happen meanwhile are not ours.
		if not own:
			return
		mutex.lock()
		errors.append(e)
		mutex.unlock()


func _tool_run_script(args: Dictionary) -> Dictionary:
	var code := String(args.get("code", "")).replace("\r\n", "\n")
	if code.strip_edges().is_empty():
		return host._err("'code' is empty.")
	var header := PackedStringArray()
	var body := code
	var full_script := RegEx.create_from_string("(?m)^func\\s+run\\s*\\(").search(code) != null
	if full_script:
		if not code.contains("@tool"):
			header.append("@tool")
		if RegEx.create_from_string("(?m)^extends\\s").search(code) == null:
			header.append("extends RefCounted")
	else:
		header.append_array(["@tool", "extends RefCounted", "", "", "func run():"])
		var lines := code.split("\n")
		var indented := PackedStringArray()
		var dedent := _common_indent(lines)
		for l in lines:
			indented.append("\t" + (l.substr(dedent) if l.length() >= dedent else l.strip_edges(true, false)))
		body = "\n".join(indented)
		if RegEx.create_from_string("\\S").search(body) == null:
			body = "\tpass"
	var offset := header.size()
	var source := ("\n".join(header) + "\n" if not header.is_empty() else "") + body + "\n"
	var capture := _Capture.new()
	OS.add_logger(capture)
	var script := GDScript.new()
	script.source_code = source
	var err := script.reload()
	if err != OK:
		OS.remove_logger(capture)
		var msgs := PackedStringArray()
		for e in capture.errors:
			var line := int(e["line"]) - offset
			msgs.append("line %d: %s" % [line, String(e["message"]).trim_prefix("Parse Error: ")] if line > 0 else String(e["message"]))
		return host._err("The script does not compile:\n" + ("\n".join(msgs) if not msgs.is_empty() else error_string(err)))
	if not script.can_instantiate():
		OS.remove_logger(capture)
		return host._err("The script compiled but cannot be instantiated.")
	var instance = script.new()
	if not instance.has_method("run"):
		OS.remove_logger(capture)
		return host._err("The script has no func run().")
	var started := Time.get_ticks_msec()
	var result = await instance.run()
	var elapsed := Time.get_ticks_msec() - started
	OS.remove_logger(capture)
	capture.mutex.lock()
	var output := capture.output.duplicate()
	var errors := capture.errors.duplicate()
	capture.mutex.unlock()
	var out := PackedStringArray()
	var result_text := var_to_str(result) if result != null else "null"
	out.append("Returned (%d ms): %s" % [elapsed, result_text.left(MAX_RESULT_CHARS)])
	if not output.is_empty():
		var joined := "\n".join(output)
		out.append("Output:\n" + (joined.right(MAX_RESULT_CHARS) if joined.length() > MAX_RESULT_CHARS else joined))
	var hard := 0
	if not errors.is_empty():
		out.append("Errors/warnings:")
		for e in errors:
			if not bool(e["warning"]):
				hard += 1
			# The script has no file, so its own frames come without a path.
			var where := ""
			var sf := String(e.get("script_file", ""))
			var ff := String(e["file"])
			if e.has("script_line") and (sf.is_empty() or sf.begins_with("gdscript://")):
				where = " (line %d)" % (int(e["script_line"]) - offset)
			elif ff.is_empty() or ff.begins_with("gdscript://"):
				if int(e["line"]) > offset:
					where = " (line %d)" % (int(e["line"]) - offset)
			elif not sf.is_empty():
				where = " (%s:%d)" % [sf, e["script_line"]]
			else:
				where = " (%s:%d)" % [ff, e["line"]]
			out.append("  %s%s%s" % ["warning: " if bool(e["warning"]) else "", e["message"], where])
	if hard > 0:
		var res: Dictionary = host._err("\n".join(out))
		return res
	return host._ok("\n".join(out))


static func _common_indent(lines: PackedStringArray) -> int:
	var best := -1
	for l in lines:
		if l.strip_edges().is_empty():
			continue
		var n := 0
		while n < l.length() and (l.substr(n, 1) == "\t" or l.substr(n, 1) == " "):
			n += 1
		if best < 0 or n < best:
			best = n
	return maxi(best, 0)


# ---------------------------------------------------------------------------
# godot_editor_log
# ---------------------------------------------------------------------------

func _tool_editor_log(args: Dictionary) -> Dictionary:
	var source := String(args.get("source", "errors"))
	var limit := clampi(int(args.get("limit", 50)), 1, 1000)
	var contains := String(args.get("contains", "")).to_lower()
	var since := int(args.get("since_id", 0))
	var out := PackedStringArray()
	if source == "output":
		var text: Variant = _output_panel_text()
		if text == null:
			return host._err("The Output panel is not available (needs the editor UI).")
		var lines := PackedStringArray()
		for l in String(text).split("\n"):
			if contains.is_empty() or l.to_lower().contains(contains):
				lines.append(l)
		if lines.size() > limit:
			lines = lines.slice(lines.size() - limit)
		return host._ok("Output panel (last %d line(s)):\n%s" % [lines.size(), "\n".join(lines)])

	if source != "debugger":
		if not AIStudioEditorLog.installed():
			out.append("Editor log: not collecting (the plugin installs it on start).")
		else:
			var kinds := "errors" if source == "errors" else "all"
			var entries := AIStudioEditorLog.entries(kinds, since)
			var shown: Array = []
			for e in entries:
				var line := _format_log_entry(e)
				if contains.is_empty() or line.to_lower().contains(contains):
					shown.append(line)
			if shown.size() > limit:
				shown = shown.slice(shown.size() - limit)
			out.append("Editor log (%s, %d of %d entries, last id %d):" % [kinds, shown.size(), entries.size(), AIStudioEditorLog.last_id()])
			for l in shown:
				out.append("  " + l)
			if shown.is_empty():
				out.append("  (nothing)")
			if bool(args.get("clear", false)):
				AIStudioEditorLog.clear()
				out.append("  (cleared)")
	if source == "errors" or source == "debugger":
		var dbg: Variant = _debugger_errors()
		if dbg == null:
			if source == "debugger":
				return host._err("The debugger panel is not available (needs the editor UI).")
		else:
			var items: Array = []
			for d in dbg:
				if contains.is_empty() or String(d).to_lower().contains(contains):
					items.append(d)
			if items.size() > limit:
				items = items.slice(items.size() - limit)
			out.append("Debugger errors (running/last game, %d):" % items.size())
			for d in items:
				out.append("  " + String(d))
			if items.is_empty():
				out.append("  (nothing)")
	return host._ok("\n".join(out))


func _format_log_entry(e: Dictionary) -> String:
	var t := String(e["type"])
	if t == "message" or t == "stderr":
		return "#%d %s %s%s" % [e["id"], e["time"], "[stderr] " if t == "stderr" else "", e["message"]]
	var where := ""
	if e.has("script_file") and not String(e["script_file"]).is_empty():
		where = " at %s:%d" % [e["script_file"], e["script_line"]]
	elif not String(e.get("file", "")).is_empty():
		where = " at %s:%d" % [e["file"], e["line"]]
	return "#%d %s %s: %s%s" % [e["id"], e["time"], t.to_upper(), e["message"], where]


func _find_by_class(node: Node, cls: String, out: Array, max_count: int = 8) -> void:
	if out.size() >= max_count:
		return
	if node.get_class() == cls:
		out.append(node)
		return
	for c in node.get_children(true):
		_find_by_class(c, cls, out, max_count)


func _editor_nodes(cls: String) -> Array:
	var found: Array = []
	if not _editor():
		return found
	var base := EditorInterface.get_base_control()
	if base == null:
		return found
	_find_by_class(base, cls, found)
	if found.is_empty() and base.get_tree() != null:
		_find_by_class(base.get_tree().root, cls, found)
	return found


func _output_panel_text() -> Variant:
	var logs := _editor_nodes("EditorLog")
	if logs.is_empty():
		return null
	var labels: Array = []
	_find_by_class(logs[0], "RichTextLabel", labels, 1)
	if labels.is_empty():
		return null
	return (labels[0] as RichTextLabel).get_parsed_text()


func _debugger_errors() -> Variant:
	var debuggers := _editor_nodes("ScriptEditorDebugger")
	if debuggers.is_empty():
		return null
	var out: Array = []
	for d in debuggers:
		var trees: Array = []
		_find_by_class(d, "Tree", trees, 32)
		for t in trees:
			var tree: Tree = t
			var root := tree.get_root()
			if root == null or tree.columns != 2:
				continue
			for item in root.get_children():
				var warn := item.has_meta("_is_warning")
				if not warn and not item.has_meta("_is_error"):
					continue
				var where := ""
				var meta = item.get_metadata(0)
				if typeof(meta) == TYPE_ARRAY and (meta as Array).size() >= 2:
					where = " at %s:%s" % [meta[0], meta[1]]
				out.append("%s %s: %s%s" % [item.get_text(0), "WARNING" if warn else "ERROR", item.get_text(1), where])
	return out
